language: python
dist: focal  # Use Ubuntu 20.04
os: linux
python:
  - "3.11"  # Specify the Python version
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=polls manage.py test
  - coverage report
  - black --check .
after_success:
  - coveralls  # Report coverage
